apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- composite-controller.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  app: cloud-endpoints-controller
  kustomize.component: cloud-endpoints
images:
- name: gcr.io/cloud-solutions-group/cloud-endpoints-controller
  newName: gcr.io/cloud-solutions-group/cloud-endpoints-controller
  newTag: 0.2.1
configMapGenerator:
- name: cloud-endpoints-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: secretName
  objref:
    kind: ConfigMap
    name: cloud-endpoints-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.secretName
- name: namespace
  objref:
    kind: ConfigMap
    name: cloud-endpoints-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml
