apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pytorch-job-crds
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pytorch-job-crds
      app.kubernetes.io/instance: pytorch-job-crds-v1.0.0
      app.kubernetes.io/version: v1.0.0
      app.kubernetes.io/component: pytorch
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/managed-by: kfctl
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: PyTorchJob
  descriptor:
    type: "pytorch-job-crds"
    version: "v1"
    description: "Pytorch-job-crds contains the \"PyTorchJob\" custom resource definition."
    maintainers:
    - name: Johnu George
      email: johnugeo@cisco.com
    owners:
    - name: Johnu George
      email: johnugeo@cisco.com
    keywords:
    - "pytorchjob"
    - "pytorch-operator"
    - "pytorch-training"
    links:
    - description: About
      url: "https://github.com/kubeflow/pytorch-operator"
    - description: Docs
      url: "https://www.kubeflow.org/docs/reference/pytorchjob/v1/pytorch/"
  addOwnerRef: true
