apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: tf-job-operator
images:
- name: gcr.io/kubeflow-images-public/tf_operator
  newName: gcr.io/kubeflow-images-public/tf_operator
  newTag: v1.0.0-g92389064
