apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- crd.yaml
commonLabels:
  app: admission-webhook
  kustomize.component: admission-webhook
namePrefix: admission-webhook-
images:
- name: gcr.io/kubeflow-images-public/admission-webhook
  newName: gcr.io/kubeflow-images-public/admission-webhook
  newTag: v1.0.0-gaf96e4e3
namespace: kubeflow
configMapGenerator:
- envs:
  - params.env
  name: admission-webhook-parameters
generatorOptions:
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: admission-webhook-parameters
- fieldref:
    fieldPath: metadata.name
  name: serviceName
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: metadata.name
  name: deploymentName
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
configurations:
- params.yaml
