apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: seldon
  app.kubernetes.io/instance: seldon-1.15
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: seldon-core-operator
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: "1.15"
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
