apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-local-gateway-service-account
  labels:
    app: cluster-local-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-multi