apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mxnet-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mxnet-operator
      app.kubernetes.io/instance: mxnet-operator-v1.0.0
      app.kubernetes.io/component: mxnet
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/version: v1.0.0
  componentKinds:
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: MXJob
  descriptor:
    type: "mxnet-operator"
    version: "v1beta1"
    description: "mxnet-operator allows users to create and manage the \"MXJob\" custom resource."
    maintainers:
    - name: Lei Su
      email: suleisl2000@hotmail.com
    owners:
    - name: Lei Su
      email: suleisl2000@hotmail.com
    keywords:
    - "MXjob"
    - "mxnet-operator"
    - "mxnet-training"
    links:
    - description: About
      url: "https://github.com/kubeflow/mxnet-operator"
  addOwnerRef: true
