apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/instance: profiles-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: profiles
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
configurations:
- overlays/istio/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
- overlays/istio/virtual-service.yaml
