version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # The default is a random time every Monday, but
      # we prefer a fixed time on Tuesdays
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_foo-6.4.1`
      # Reason: docker image tags can't contain slashes, so
      # Helium will fail to provision any dependabot PRs
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/backend/src/proto"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/live-automation"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/load-tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
