dist: trusty
sudo: required
services:
- docker
cache:
  directories:
    - /home/travis/.cache/go-build
language: go
go:
- 1.10beta1
env:
- BUCKET=MISC
# If you want to update the number of PPS workers, you'll need to update
# the value in ./etc/build/PPS_BUILD_BUCKET_COUNT
- BUCKET=PPS1
- BUCKET=PPS2
- BUCKET=PPS3
branches:
  except:
    - /^v[0-9]/
before_install:
- sudo etc/testing/ci/before_install.sh
before_script:
- docker version
# Install any deps used by our "batch test" cron
- etc/testing/ci/travis_install_batch_deps.sh
script:
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
