dist: xenial
sudo: required
services:
- docker
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/cached-deps
language: go
go:
- "1.11.1"
env:
  global:
    - PATH=$HOME/cached-deps:$PATH
  matrix:
    - BUCKET=MISC
    # If you want to update the number of PPS workers, you'll also need to update
    # the value in ./etc/build/PPS_BUILD_BUCKET_COUNT
    - BUCKET=PPS1
    - BUCKET=PPS2
    - BUCKET=PPS3
    - BUCKET=EXAMPLES
before_install:
- sudo etc/testing/travis_before_install.sh
before_script:
- docker version
script:
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
- kubectl describe pod -l suite=pachyderm,app=etcd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
