dist: xenial
sudo: required
cache:
  directories:
    # If any directories are added here, they must also be added to
    # etc/testing/travis_cache.sh
    - ${HOME}/.cache
    - ${HOME}/cached-deps
    - ${HOME}/gopath/pkg/mod
    - "$(python3 -c 'import site; print(site.USER_BASE)')"
    - ${HOME}/docker_images

language: go
go:
  - "1.13.1"
env:
  global:
    - PATH="${HOME}/cached-deps:$(python3 -c 'import site; print(site.USER_BASE)')/bin:${PATH}"
    - PPS_BUCKETS=6
    - AUTH_BUCKETS=2
    - GOPROXY=https://proxy.golang.org
  matrix:
    - BUCKET=MISC
    # If you want to update the number of PPS or auth buckets, you'll neet to
    # update the value of PPS_BUCKETS or AUTH_BUCKETS above
    - BUCKET=ADMIN
    - BUCKET=AUTH1
    - BUCKET=AUTH2
    - BUCKET=PFS
    - BUCKET=PPS1
    - BUCKET=PPS2
    - BUCKET=PPS3
    - BUCKET=PPS4
    - BUCKET=PPS5
    - BUCKET=PPS6
    - BUCKET=EXAMPLES

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: etc/testing/travis_build.sh

before_install:
  # Make sure we are looking at the commit we're supposed to be testing. It's
  # possible that we've been fast-forwarded to a newer commit, which causes
  # weird concurrency issues like trying to pull a docker image that hasn't
  # been pushed yet. NB: I'm not convinced that this will help, on reflection,
  # as the pachctl binary may actually come from a cache from a future build.
  # Hmm.
  - (cd pachyderm/pachyderm; echo "checking out ${TRAVIS_COMMIT}"; git checkout ${TRAVIS_COMMIT})
  # Make sure cache dirs exist and are writable
  - etc/testing/travis_cache.sh
install:
  - etc/testing/travis_install.sh
script: travis_retry bash -c "timeout 9m etc/testing/travis.sh; status=$?; if [ $status -ne 0 ]; then etc/testing/kube_debug.sh; fi; exit $status"
before_cache:
  # Make sure cache dirs have the necessary permissions for Travis to traverse
  # & copy them all elsewhere
  - etc/testing/travis_cache.sh

after_failure:
  - kubectl version
  - kubectl get all
  - kubectl get all --namespace kafka
  - kubectl describe pod -l app=pachd
  - kubectl describe pod -l suite=pachyderm,app=etcd
  - kubectl logs -l app=pachd | tail -n 100
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
branches:
  only:
  # Trigger only for PR's to master
  - master
  # Trigger CI tests for all release branches
  # Eg. 1.9.x, 1.10.x
  - /^\d+\.\d+\.x/
  # Trigger CI tests for all branches that end with "-ci-trigger"
  # ruby reg-ex except for things before/after "/"
  - /.*(?i:ci-trigger)$/
  # For all branches uncomment the line below or remove the "branches" section
  #- /.*/
