dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.8
branches:
  except:
    - /^v[0-9]/
before_install:
- echo 'DOCKER_OPTS="-H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker
  > /dev/null
- sudo apt-get install -qq pkg-config fuse
- sudo modprobe fuse
- sudo chmod 666 /dev/fuse
- sudo cp etc/build/fuse.conf /etc/fuse.conf
- sudo chown root:$USER /etc/fuse.conf
- sudo mkdir -p /var/lib/kubelet
- sudo mount -o bind /var/lib/kubelet /var/lib/kubelet
- sudo mount --make-shared /var/lib/kubelet
before_script:
- wget https://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/
- make launch-kube
- kubectl get all
- docker version
script:
- make lint
- make docker-build clean-launch-dev launch-dev test-pfs test-pps test-hashtree
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
