dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.7
branches:
  except:
    - /^v[0-9]/
before_install:
- echo 'DOCKER_OPTS="-H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker
  > /dev/null
- sudo apt-get install -qq pkg-config fuse
- sudo modprobe fuse
- sudo chmod 666 /dev/fuse
- sudo cp etc/build/fuse.conf /etc/fuse.conf
- sudo chown root:$USER /etc/fuse.conf
- sudo mkdir -p /var/lib/kubelet
- sudo mount -o bind /var/lib/kubelet /var/lib/kubelet
- sudo mount --make-shared /var/lib/kubelet
before_script:
- wget https://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/
- make launch-kube
- kubectl get all
- docker version
# kops and aws only needed by bench suite
- wget https://github.com/kubernetes/kops/releases/download/1.5.1/kops-linux-amd64
- chmod +x kops-linux-amd64
- mv kops-linux-amd64 /usr/local/bin/kops
- python3 --version
- pip --version
- pip install awscli --upgrade --user
- aws --version
- sudo apt-get install uuid
script:
- make lint
- ./etc/build/travis.sh
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
