{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.dash.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: dash
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      labels:
        app: dash
        suite: pachyderm
        {{- if .Values.dash.podLabels }}
        {{- toYaml .Values.dash.podLabels | nindent 8 }}
        {{- end }}
      name: dash
      namespace: {{ .Release.Namespace }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | quote }}
      {{- end }}
      containers:
      - image: "{{ .Values.dash.image.repository }}:{{ .Values.dash.image.tag }}"
        imagePullPolicy: {{ .Values.dash.image.pullPolicy }}
        name: dash
        ports:
        - containerPort: {{ .Values.dash.config.graphqlPort }}
          name: dash-http
        env:
        - name: ISSUER_URI
          value: {{ .Values.dash.config.issuerURI | quote}}
        - name: OAUTH_REDIRECT_URI
          value: {{ .Values.dash.config.oauthRedirectURI | quote }}
        - name: OAUTH_CLIENT_ID
          value: {{ .Values.dash.config.oauthClientID | quote }}
        - name: OAUTH_CLIENT_SECRET
          value: {{ include "pachyderm.dashSecret" . | quote }}
        - name: GRAPHQL_PORT
          value: {{ .Values.dash.config.graphqlPort | quote }}
        - name: OAUTH_PACHD_CLIENT_ID
          value: {{ .Values.dash.config.oauthPachdClientID | quote }}
        - name: PACHD_ADDRESS
          value: {{ .Values.dash.config.pachdAddress | quote }}
        {{- if .Values.dash.resources }}
        resources: {{ toYaml .Values.dash.resources | nindent 10 }}
        {{- end }}
{{ end -}}
