{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and .Values.dash.enabled .Values.dash.ingress.enabled -}}
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "dash"
  annotations: {{ toYaml .Values.dash.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "dash"
    suite: "pachyderm"
spec:
  {{- if .Values.dash.ingress.tls.enabled }}
  tls:
    - secretName: {{ required "if dash.ingress.tls.enabled you must specify dash.ingress.tls.secretName" .Values.dash.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ required "dash.ingress.host is required when dash.ingress.enabled" .Values.dash.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "dash"
              servicePort: "dash-http"
          - path: "/dex"
            backend:
              serviceName: "pachd"
              servicePort: "identity-port"
          - path: "/authorization-code/callback"
            backend:
              serviceName: "pachd"
              servicePort: "oidc-port"
{{ end -}}
