{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- /* Sanity check to ensure .create set if .crt or .key set  */ -}}
{{- if and (not .Values.ingress.tls.newSecret.create) .Values.ingress.tls.newSecret.crt }}
  {{ fail "Must set ingress.tls.newSecret.create to true when specifying ingress.tls.newSecret.crt "}}
{{ end -}}
{{- if and (not .Values.ingress.tls.newSecret.create) .Values.ingress.tls.newSecret.key }}
  {{ fail "Must set ingress.tls.newSecret.create to true when specifying ingress.tls.newSecret.key "}}
{{ end -}}
{{- if .Values.dash.enabled -}}
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.newSecret.create }}
apiVersion: "v1"
data:
  tls.crt: {{ required "If ingress.tls.newSecret.create, you must specify a cert at ingress.tls.newSecret.crt" .Values.ingress.tls.newSecret.crt | b64enc | quote }}
  tls.key: {{ required "If ingress.tls.newSecret.create, you must specify a key at ingress.tls.newSecret.key" .Values.ingress.tls.newSecret.key | b64enc | quote }}
kind: Secret
metadata:
  labels:
    app: "dash"
    suite: "pachyderm"
  name: {{ required "When ingress.tls.enabled you must specify ingress.tls.secretName" .Values.ingress.tls.secretName | quote }}
{{ end -}}
{{ end -}}
