{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and .Values.pachd.rbac.create .Values.pachd.rbac.clusterRBAC .Values.pachd.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ""
    suite: pachyderm
  name: {{ include "pachd.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: pachyderm
subjects:
- kind: ServiceAccount
  name: {{ .Values.pachd.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace }}
{{ end -}}
