{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- /* Deploy even if console is disabled, so the lack of endpoints is more easily apparent. */ -}}
{{- if and .Values.proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pachyderm-proxy-support
    suite: pachyderm
  name: console-proxy-backend
  namespace: {{ .Release.Namespace }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: console-http
    port: 4000
    targetPort: console-http
  selector:
    app: console
    suite: pachyderm
  type: ClusterIP
  clusterIP: None
{{- end }}
