apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
commonLabels:
  kustomize.component: mxnet-operator
images:
- name: mxjob/mxnet-operator
  newName: mxjob/mxnet-operator
  newTag: v1beta1
