{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.dash.url -}}
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "dash"
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
    app: "dash"
    suite: "pachyderm"
spec:
  {{- if .Values.dash.tls.enabled }}
  tls:
    - secretName: {{ required "if dash.tls.enabled you must specify dash.tls.secretName" .Values.dash.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.dash.url | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "dash"
              servicePort: "dash-http"
          - path: "/dex"
            backend:
              serviceName: "pachd"
              servicePort: "identity-port"
          - path: "/authorization-code/callback"
            backend:
              serviceName: "pachd"
              servicePort: "oidc-port"
{{ end -}}
