{{- /*
SPDX-FileCopyrightText: 2021 Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: dash-http
    {{- if eq .Values.dash.service.type "NodePort" }}
    nodePort: 30080
    {{- end }}
    port: 8080
  - name: grpc-proxy-http
    {{- if eq .Values.dash.service.type "NodePort" }}
    nodePort: 30081
    {{- end }}
    port: 8081
  selector:
    app: dash
    suite: pachyderm
  type: {{ .Values.dash.service.type }}
