{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
    {{- if .Values.dash.service.labels }}
    {{- toYaml .Values.dash.service.labels | nindent 4 }}
    {{- end }}
  name: dash
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: dash-http
    {{- if eq .Values.dash.service.type "NodePort" }}
    nodePort: 30080
    {{- end }}
    port: 4000
  selector:
    app: dash
    suite: pachyderm
  type: {{ .Values.dash.service.type }}
