apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/instance: tf-job-operator-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: tf-job-operator
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
