# pachctl deploy local --dry-run -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/log
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resourceNames:
  - pachyderm-storage-secret
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm
  namespace: default
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: pachyderm
subjects:
- kind: ServiceAccount
  name: pachyderm
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd
        suite: pachyderm
      name: etcd
      namespace: default
    spec:
      containers:
      - command:
        - /usr/local/bin/etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://0.0.0.0:2379
        - --data-dir=/var/data/etcd
        - --auto-compaction-retention=1
        - --max-txn-ops=5000
        - --quota-backend-bytes=8589934592
        image: quay.io/coreos/etcd:v3.3.5
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        resources:
          limits:
            cpu: 250m
            memory: 512M
          requests:
            cpu: 250m
            memory: 512M
        volumeMounts:
        - mountPath: /var/data/etcd
          name: etcd-storage
      volumes:
      - hostPath:
          path: /var/pachyderm/etcd
        name: etcd-storage
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: default
spec:
  ports:
  - name: client-port
    nodePort: 32379
    port: 2379
    targetPort: 0
  selector:
    app: etcd
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: default
spec:
  ports:
  - name: api-grpc-port
    nodePort: 30650
    port: 650
    targetPort: 0
  - name: trace-port
    nodePort: 30651
    port: 651
    targetPort: 0
  - name: api-http-port
    nodePort: 30652
    port: 652
    targetPort: 0
  - name: saml-port
    nodePort: 30654
    port: 654
    targetPort: 0
  - name: api-git-port
    nodePort: 30999
    port: 999
    targetPort: 0
  - name: s3gateway-port
    nodePort: 30600
    port: 600
    targetPort: 0
  selector:
    app: pachd
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pachd
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: ""
      creationTimestamp: null
      labels:
        app: pachd
        suite: pachyderm
      name: pachd
      namespace: default
    spec:
      containers:
      - env:
        - name: PACH_ROOT
          value: /pach
        - name: ETCD_PREFIX
        - name: NUM_SHARDS
          value: "16"
        - name: STORAGE_BACKEND
          value: LOCAL
        - name: STORAGE_HOST_PATH
          value: /var/pachyderm/pachd
        - name: WORKER_IMAGE
          value: pachyderm/worker:1.9.3
        - name: IMAGE_PULL_SECRET
        - name: WORKER_SIDECAR_IMAGE
          value: pachyderm/pachd:1.9.3
        - name: WORKER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: PACHD_VERSION
          value: 1.9.3
        - name: METRICS
          value: "true"
        - name: LOG_LEVEL
          value: info
        - name: BLOCK_CACHE_BYTES
          value: 256M
        - name: IAM_ROLE
        - name: NO_EXPOSE_DOCKER_SOCKET
          value: "false"
        - name: PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING
          value: "false"
        - name: PACHD_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PACHD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: pachd
              divisor: "0"
              resource: requests.memory
        - name: EXPOSE_OBJECT_API
          value: "false"
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: minio-endpoint
              name: pachyderm-storage-secret
              optional: true
        - name: MINIO_ID
          valueFrom:
            secretKeyRef:
              key: minio-id
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_REGION
          valueFrom:
            secretKeyRef:
              key: amazon-region
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_ID
          valueFrom:
            secretKeyRef:
              key: amazon-id
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_SECRET
          valueFrom:
            secretKeyRef:
              key: amazon-secret
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_VAULT_ADDR
          valueFrom:
            secretKeyRef:
              key: amazon-vault-addr
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: amazon-vault-token
              name: pachyderm-storage-secret
              optional: true
        - name: CUSTOM_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: custom-endpoint
              name: pachyderm-storage-secret
              optional: true
        - name: GOOGLE_BUCKET
          valueFrom:
            secretKeyRef:
              key: google-bucket
              name: pachyderm-storage-secret
              optional: true
        - name: MICROSOFT_SECRET
          valueFrom:
            secretKeyRef:
              key: microsoft-secret
              name: pachyderm-storage-secret
              optional: true
        - name: MINIO_SECURE
          valueFrom:
            secretKeyRef:
              key: minio-secure
              name: pachyderm-storage-secret
              optional: true
        - name: MINIO_SIGNATURE
          valueFrom:
            secretKeyRef:
              key: minio-signature
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_BUCKET
          valueFrom:
            secretKeyRef:
              key: amazon-bucket
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_TOKEN
          valueFrom:
            secretKeyRef:
              key: amazon-token
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_DISTRIBUTION
          valueFrom:
            secretKeyRef:
              key: amazon-distribution
              name: pachyderm-storage-secret
              optional: true
        - name: GOOGLE_CRED
          valueFrom:
            secretKeyRef:
              key: google-cred
              name: pachyderm-storage-secret
              optional: true
        - name: MINIO_BUCKET
          valueFrom:
            secretKeyRef:
              key: minio-bucket
              name: pachyderm-storage-secret
              optional: true
        - name: MICROSOFT_CONTAINER
          valueFrom:
            secretKeyRef:
              key: microsoft-container
              name: pachyderm-storage-secret
              optional: true
        - name: MICROSOFT_ID
          valueFrom:
            secretKeyRef:
              key: microsoft-id
              name: pachyderm-storage-secret
              optional: true
        - name: MINIO_SECRET
          valueFrom:
            secretKeyRef:
              key: minio-secret
              name: pachyderm-storage-secret
              optional: true
        - name: AMAZON_VAULT_ROLE
          valueFrom:
            secretKeyRef:
              key: amazon-vault-role
              name: pachyderm-storage-secret
              optional: true
        image: pachyderm/pachd
        imagePullPolicy: IfNotPresent
        name: pachd
        ports:
        - containerPort: 650
          name: api-grpc-port
          protocol: TCP
        - containerPort: 651
          name: trace-port
        - containerPort: 652
          name: api-http-port
          protocol: TCP
        - containerPort: 653
          name: peer-port
          protocol: TCP
        - containerPort: 999
          name: api-git-port
          protocol: TCP
        - containerPort: 654
          name: saml-port
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /pachd
            - --readiness
        resources:
          limits:
            cpu: 250m
            memory: 512M
          requests:
            cpu: 250m
            memory: 512M
        volumeMounts:
        - mountPath: /pach
          name: pach-disk
        - mountPath: /pachyderm-storage-secret
          name: pachyderm-storage-secret
      serviceAccountName: pachyderm
      volumes:
      - hostPath:
          path: /var/pachyderm/pachd
        name: pach-disk
      - name: pachyderm-storage-secret
        secret:
          secretName: pachyderm-storage-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: default
spec:
  ports:
  - name: dash-http
    nodePort: 30080
    port: 8080
    targetPort: 0
  - name: grpc-proxy-http
    nodePort: 30081
    port: 8081
    targetPort: 0
  selector:
    app: dash
    suite: pachyderm
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: default
spec:
  selector:
    matchLabels:
      app: dash
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dash
        suite: pachyderm
      name: dash
      namespace: default
    spec:
      containers:
      - image: pachyderm/dash:1.9.0
        imagePullPolicy: IfNotPresent
        name: dash
        ports:
        - containerPort: 8080
          name: dash-http
        resources: {}
      - image: pachyderm/grpc-proxy:0.4.6
        imagePullPolicy: IfNotPresent
        name: grpc-proxy
        ports:
        - containerPort: 8081
          name: grpc-proxy-http
        resources: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: pachyderm-storage-secret
    suite: pachyderm
  name: pachyderm-storage-secret
  namespace: default
---
