apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pipelines-runner
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ''
    keywords:
    - pipelines-runner
    - kubeflow
    links:
    - description: About
      url: ''
    maintainers: []
    owners: []
    type: pipelines-runner
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: pipelines-runner
      app.kubernetes.io/instance: pipelines-runner-0.2.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pipelines-runner
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.2.0
