varReference:
- path: spec/template/spec/containers/env/value
  kind: StatefulSet
- path: spec/filters/filterConfig/httpService/serverUri/uri
  kind: EnvoyFilter
- path: spec/filters/filterConfig/httpService/serverUri/cluster
  kind: EnvoyFilter