apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: basic-auth-ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: basic-auth-ingress
      app.kubernetes.io/instance: basic-auth-ingress-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: basic-auth-ingress
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: basic-auth-ingress
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
     - basic-auth-ingress
     - kubeflow
    links:
    - description: About
      url: ""
  addOwnerRef: true
