apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: basic-auth-ingress
  app.kubernetes.io/instance: basic-auth-ingress-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: basic-auth-ingress
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
