[build]
  base = "doc/"
  command = "./build.sh"
  publish = "site/"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]

  entryPoints = [
    "latest/index.html",
  ]
 
  recursive = true
  pretty = true
 
  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = ["404.html"]
 
  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  checkExternal = false
  followSourceMaps = false

[[redirects]]
  from = "/"
  to = "/latest/"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/index.html"
  to = "/latest/"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/cookbook/combining.html"
  to = "https://docs.pachyderm.com/latest/examples/examples/#lazy-shuffle-pipeline"
  status = 301
  force = true

[[redirects]]
  from = "/en/latest/*"
  to = "/latest/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/archive/*"
  to = "/latest/archive/"
  status = 301
  force = true

[[redirects]]
  from = "/1.10.x/*"
  to = "/latest/archive/"
  status = 301
  force = true

[[redirects]]
  from = "/1.9.x/*"
  to = "/latest/archive/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.pachyderm.io/*"
  to = "https://docs.pachyderm.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/getting_started/*"
  to = "/latest/getting_started/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/concepts/*"
  to = "/latest/concepts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/:version/how-tos/basic-data-operations/export-data-out-pachyderm/"
  to = "/:version/how-tos/basic-data-operations/export-data-out-pachyderm/export-data-pachctl/"
  status = 301
  force = true

[[redirects]]
  from = "/:version/how-tos/pipeline-operations/"
  to = "/:version/how-tos/pipeline-operations/create-pipeline/"
  status = 301
  force = true

[[redirects]]
  from = "/2.0.x/how-tos/advanced-data-operations/splitting-data/*"
  to = "/latest/"
  status = 301
  force = true 

[[redirects]]
  from = "/latest/how-tos/use-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/use-jupyterhub/using-jupyterhub/"
  to = "/latest/how-tos/use-pachyderm-ide/using-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/distributed_computing/"
  to = "/latest/concepts/advanced-concepts/distributed_computing/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/deferred_processing/"
  to = "/latest/concepts/advanced-concepts/deferred_processing/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/load-data-into-pachyderm/"
  to = "/latest/how-tos/basic-data-operations/load-data-into-pachyderm/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/export-data-out-pachyderm/*"
  to = "/latest/how-tos/basic-data-operations/export-data-out-pachyderm/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/removing_data_from_pachyderm/"
  to = "/latest/how-tos/basic-data-operations/removing_data_from_pachyderm/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/ingressing_from_diff_cloud/"
  to = "/latest/how-tos/basic-data-operations/ingressing_from_diff_cloud/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/splitting-data/*"
  to = "/latest/how-tos/advanced-data-operations/splitting-data/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/mount-volume/"
  to = "/latest/how-tos/advanced-data-operations/mount-volume/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/time_windows/"
  to = "/latest/how-tos/advanced-data-operations/time_windows/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/use-transactions-to-run-multiple-commands/"
  to = "/latest/how-tos/advanced-data-operations/use-transactions-to-run-multiple-commands/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/err_cmd/"
  to = "/latest/how-tos/advanced-data-operations/err_cmd/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/create-pipeline/"
  to = "/latest/how-tos/pipeline-operations/create-pipeline/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/run_pipeline/"
  to = "/latest/how-tos/pipeline-operations/run_pipeline/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/updating_pipelines/"
  to = "/latest/how-tos/pipeline-operations/updating_pipelines/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/delete-pipeline/"
  to = "/latest/how-tos/pipeline-operations/delete-pipeline/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/monitor-job-progress/"
  to = "/latest/how-tos/pipeline-operations/monitor-job-progress/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how-tos/create-ml-workflow/"
  to = "/latest/how-tos/developer-workflow/create-ml-workflow/"
  status = 301
  force = true

[[redirects]]
  from = "/how-tos/*"
  to = "/latest/how-tos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/hub/hub_getting_started/"
  to = "/latest/hub/hub_getting_started/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/pachhub/pachhub_getting_started/"
  to = "/latest/hub/hub_getting_started/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/deploy-manage/deploy/deploy-pachyderm-jupyterhub/"
  to = "/latest/deploy-manage/deploy/deploy-pachyderm-ide/"
  status = 301
  force = true

[[redirects]]
  from = "/latest/deploy-manage/deploy/migrations/"
  to = "/latest/deploy-manage/manage/migrations/"
  status = 301
  force = true

[[redirects]]
  from = "/deploy-manage/*"
  to = "/latest/deploy-manage/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/reference/*"
  to = "/latest/reference/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/enterprise/saml/"
  to = "/latest/enterprise/auth/saml/saml/"
  status = 301
  force = true

[[redirects]]
  from = "/enterprise/*"
  to = "/latest/enterprise/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/troubleshooting/*"
  to = "/latest/troubleshooting/:splat"
  status = 301
  force = true

[[redirects]]
    from = "/contributing/*"
    to = "/latest/contributing/:splat"
    status = 301
    force = true