apiVersion: v1
kind: Service
metadata:
  name: cluster-local-gateway
  annotations:
  labels:
    app: cluster-local-gateway
    istio: cluster-local-gateway
spec:
  type: ClusterIP
  selector:
    app: cluster-local-gateway
    istio: cluster-local-gateway
  ports:
    -
      name: http2
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
    -
      name: tcp
      port: 31400
    -
      name: tcp-pilot-grpc-tls
      port: 15011
      targetPort: 15011
    -
      name: tcp-citadel-grpc-tls
      port: 8060
      targetPort: 8060
    -
      name: http2-kiali
      port: 15029
      targetPort: 15029
    -
      name: http2-prometheus
      port: 15030
      targetPort: 15030
    -
      name: http2-grafana
      port: 15031
      targetPort: 15031
    -
      name: http2-tracing
      port: 15032
      targetPort: 15032
