apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: spark-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/instance: spark-operator-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: sppark-operator
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ConfigMap
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: SparkOperator
  descriptor:
    type: "spark-operator"
    version: "v1"
    description: "Spark-operator allows users to create and manage the \"SparkApplication\" custom resource."
    maintainers:
    - name: Holden Karau
      email: holden@pigscanfly.ca
    owners:
    - name: Holden Karau
      email: holden@pigscanfly.ca
    keywords:
    - "spark"
  addOwnerRef: true
