apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubebench
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubebench
      app.kubernetes.io/instance: kubebench-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: kubebench
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    type: kubebench
    version: v1beta1
    description: "Makes it easy to run benchmark jobs on Kubeflow with various system and model settings"
    maintainers: []
    owners: []
    keywords:
     - kubebench
     - kubeflow
    links:
    - description: About
      url: https://github.com/kubeflow/kubebench
  addOwnerRef: true
