{{- /*
SPDX-FileCopyrightText: 2021 Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: client-port
    {{- if eq .Values.etcd.service.type "NodePort" }}
    nodePort: 32379
    {{- end }}
    port: 2379
    targetPort: client-port

  selector:
    app: etcd
  type: {{ .Values.etcd.service.type }}
