---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
spec:
  ports:
  - name: client-port
    port: 2379
    targetPort: client-port
  selector:
    app: etcd
  type: NodePort #TODO ClusterIP
