apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: api-service
  app.kubernetes.io/instance: api-service-0.2.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: api-service
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.2.0
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
