apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubeflow
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeflow
      app.kubernetes.io/instance: kubeflow-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: kubeflow
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  componentKinds:
    - group: app.k8s.io
      kind: Application
  descriptor: 
    type: kubeflow
    version: v1beta1
    description: application that aggregates all kubeflow applications
    maintainers:
    - name: Jeremy Lewi
      email: jlewi@google.com
    - name: Kam Kasravi
      email: kam.d.kasravi@intel.com
    owners:
    - name: Jeremy Lewi
      email: jlewi@google.com
    keywords:
     - kubeflow
    links:
    - description: About
      url: "https://kubeflow.org"
  addOwnerRef: true
