# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0

pachd:
  storage:
    backend: "LOCAL"
dash:
  config:
    issuerURI: "http://localhost:30658/"
    oauthRedirectURI: "http://localhost:4000/oauth/callback/?inline=true"
    oauthClientID: "dash"
    oauthClientSecret: "abc"
    graphqlPort: 4000
    oauthPachdClientID: "pachd"
    pachdAddress: "pachd-peer.default.svc.cluster.local:30653"
