# SPDX-FileCopyrightText: 2021 Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0

pachd:
  storage:
    backend: "MINIO"
    minio:
      bucket: "foo"
      endpoint: "https://bar.test/"
      id: "baz"
      secret: "quux"
      secure: "quuux"
      signature: "quuuux"
