{{- if .Values.oidc.deployDex }}
{{- /*
  SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
  SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dex
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-dex
    release: {{ .Release.Name }}
    release-namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 5556
    protocol: TCP
    targetPort: http
  - appProtocol: http
    name: telemetry
    port: 5558
    protocol: TCP
    targetPort: telemetry
  selector:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
  sessionAffinity: None
  type: ClusterIP
{{- end }}