apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
nameprefix: ml-pipeline-viewer-
commonLabels:
  app: ml-pipeline-viewer-crd
resources:
- crd.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
images:
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newTag: '0.1.23'
