# Install packages required for building debian packages
---
- apt: pkg={{ item }} state=present
  with_items:
    - cdbs
    - debhelper
    - devscripts
    - dpkg-dev
    - software-properties-common
    - devscripts
    - build-essential
    - lintian
- gem: name={{ item }} state=present
  with_items:
    - fpm
    - package_cloud
