{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    suite: pachyderm
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: client-port
    port: 5432
    {{- if eq .Values.postgresql.service.type "NodePort" }}
    nodePort: 32228
    {{- end }}
    targetPort: client-port
  selector:
    app: postgres
  type: {{ .Values.postgresql.service.type }}
