{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and .Values.console.enabled   (not .Values.console.config.oauthClientSecretSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: console
    suite: pachyderm
  name: pachyderm-console-secret
  namespace: {{ .Release.Namespace }}
data:
{{ if .Release.IsUpgrade }}
  OAUTH_CLIENT_SECRET: {{ required "For an upgrade release, a value is required for console.config.oauthClientSecret" .Values.console.config.oauthClientSecret | toString | b64enc | quote }}
{{ else }}
  OAUTH_CLIENT_SECRET: {{ default (randAlphaNum 32) .Values.console.config.oauthClientSecret | toString | b64enc | quote }}
{{- end -}}
{{- end }}
