{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.console.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: console
    suite: pachyderm
  name: pachyderm-console-secret
  namespace: {{ .Release.Namespace }}
data:
{{- if .Release.IsUpgrade }}
  OAUTH_CLIENT_SECRET: {{ .Values.console.config.oauthClientSecret | toString | b64enc | quote }}
{{- else }}
  OAUTH_CLIENT_SECRET: {{ default (randAlphaNum 32) .Values.console.config.oauthClientSecret | toString | b64enc | quote }}
{{- end -}}
{{- end }}
