apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: persistent-agent
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ''
    keywords:
    - persistent-agent
    - kubeflow
    links:
    - description: About
      url: ''
    maintainers: []
    owners: []
    type: persistent-agent
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: persistent-agent
      app.kubernetes.io/instance: persistent-agent-0.2.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: persistent-agent
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.2.0
