apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: kubeflow
  app.kubernetes.io/instance: kubeflow
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: kubeflow
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
