{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.ingress.enabled -}}
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "console"
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "console"
    suite: "pachyderm"
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ required "if ingress.tls.enabled you must specify ingress.tls.secretName" .Values.ingress.tls.secretName }}
      hosts:
       - {{ required "ingress.host is required when ingress.enabled" .Values.ingress.host | quote }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host is required when ingress.enabled" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/dex"
            pathType: Prefix
            backend:
              service:
              {{- if .Values.enterpriseServer.enabled }}
                name: "pach-enterprise"
              {{- else }}
                name: "pachd"
              {{- end }}
                port:
                  name: "identity-port"
          - path: "/authorization-code/callback"
            pathType: Prefix
            backend:
              service:
              {{- if .Values.enterpriseServer.enabled }}
                name: "pach-enterprise"
              {{- else }}
                name: "pachd"
              {{- end }}
                port:
                  name: "oidc-port"
          {{- if .Values.console.enabled }}
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "console"
                port:
                  name: "console-http"
          {{- end }}
{{ end -}}
