{{- if .Values.determined.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: determined-master-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: determined-master-{{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ required "A valid Values.determined.masterPort entry required!" .Values.determined.masterPort }}
    targetPort: {{- include "determined.masterPort" . | indent 1 }}
    protocol: TCP
  {{- if .Values.determined.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.determined.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}

{{- if ((.Values.determined.openshiftRoute).enabled | default false) }}
  type: ClusterIP
{{- else }}
  type: {{ if (.Values.determined.useNodePortForMaster | default false) }}NodePort{{ else }}LoadBalancer{{ end }}
{{- end }}
  selector:
    app: determined-master-{{ .Release.Name }}
{{- end }}