apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- virtual-service.yaml
configMapGenerator:
- name: tektoncd-install-istio-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: clusterDomain
  objref:
    kind: ConfigMap
    name: tektoncd-install-istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterDomain
- name: namespace
  objref:
    kind: ConfigMap
    name: tektoncd-install-istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml
