apiVersion: v1
kind: Service
metadata:
  name: katib-mysql
  labels:
    app: katib
    component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    app: katib
    component: mysql
