apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- deployment.yaml
- service.yaml
- template.yaml
- authzadaptor.yaml
- handler.yaml
- instance.yaml
- rule.yaml
commonLabels:
  kustomize.component: aws-authzadaptor
images:
- name: seedjeffwan/istio-adapter
  newName: seedjeffwan/istio-adapter
  newTag: "0.1"
configMapGenerator:
  - name: aws-authzadaptor-parameters
    env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: aws-authzadaptor-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.istio-namespace
- name: origin-header
  objref:
    kind: ConfigMap
    name: aws-authzadaptor-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.origin-header
- name: custom-header
  objref:
    kind: ConfigMap
    name: aws-authzadaptor-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.custom-header
configurations:
- params.yaml