apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kf-admin-basic-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kf-admin-basic-auth
subjects:
- kind: ServiceAccount
  name: kf-admin
  namespace: $(istioNamespace)
