varReference:
- path: metadata/name
  kind: Certificate
- path: metadata/annotations/getambassador.io\/config
  kind: Service
- path: spec/dnsNames
  kind: Certificate
- path: spec/issuerRef/name
  kind: Certificate
- path: metadata/annotations/kubernetes.io\/ingress.global-static-ip-name
  kind: Ingress
- path: spec/commonName
  kind: Certificate
- path: spec/secretName
  kind: Certificate
- path: spec/acme/config/domains
  kind: Certificate
- path: spec/acme/config/http01/ingress
  kind: Certificate
- path: metadata/name
  kind: Ingress
- path: metadata/annotations/certmanager.k8s.io\/issuer
  kind: Ingress
- path: metadata/name
  kind: CloudEndpoint
- path: spec/project
  kind: CloudEndpoint
- path: spec/targetIngress/name
  kind: CloudEndpoint
- path: spec/targetIngress/namespace
  kind: CloudEndpoint
- path: spec/domains
  kind: ManagedCertificate
- path: subjects/namespace
  kind: ClusterRoleBinding
