apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
- overlays/istio
commonLabels:
  app.kubernetes.io/component: jupyter
  app.kubernetes.io/instance: jupyter-web-app
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: jupyter-web-app
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
