apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- certificate.yaml

configMapGenerator:
- name: ingressgateway-self-signed-cert-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: domain
  objref:
    kind: ConfigMap
    name: ingressgateway-self-signed-cert-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.domain
configurations:
- params.yaml
