apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jupyter-web-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter-web-app
      app.kubernetes.io/instance: jupyter-web-app
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: jupyter
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.6
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: core
    kind: ServiceAccount
  - group: networking.istio.io
    kind: VirtualService
  descriptor:
    type: jupyter-web-app
    version: v0.6.2
    description: Provides a UI which allows the user to create/conect/delete jupyter notebooks.
    maintainers:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
    owners:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
    keywords:
     - jupyterhub
     - jupyter ui
     - notebooks  
    links:
    - description: About
      url: https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app
    - description: Docs
      url: https://www.kubeflow.org/docs/notebooks 
  addOwnerRef: true

