{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and (include "pachyderm.enterpriseLicenseKeySecretName" .) .Values.pachd.activateAuth }} 
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-auth
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if not .Values.pachd.rootTokenSecretName }}
  root-token: {{ default (randAlphaNum 32) .Values.pachd.rootToken }}
  {{- end }}
  auth-config: |
    client_id: {{ required "For Authentication, an OIDC Client ID for this pachd must be set." .Values.pachd.oauthClientID }}
    issuer: {{ include "pachyderm.issuerURI" . }}
    localhost_issuer: {{ include "pachyderm.localhostIssuer" . }}
    require_email_verified: {{ .Values.oidc.requireVerifiedEmail }}
    {{- if include "pachyderm.userAccessibleOauthIssuerHost" . }}
    user_accessible_issuer_host: {{ include "pachyderm.userAccessibleOauthIssuerHost" . }}
    {{- end }}
    redirect_uri: {{ include "pachyderm.pachdRedirectURI" . }}
    scopes:
    - email
    - profile
    - groups
    - openid
{{ if not .Values.pachd.oauthClientSecretSecretName }}
  pachd-oauth-client-secret: {{ default (randAlphaNum 32) .Values.pachd.oauthClientSecret }}
{{ end }}
{{ if or (include  "pachyderm.mockIDPRoleBindings" .) .Values.pachd.pachAuthClusterRoleBindings }}
  cluster-role-bindings: |
    {{- if (include  "pachyderm.mockIDPRoleBindings" .)}}
{{ (include  "pachyderm.mockIDPRoleBindings" .) | indent 4 }}
    {{- end }}
    {{- if .Values.pachd.pachAuthClusterRoleBindings }}
{{ toYaml .Values.pachd.pachAuthClusterRoleBindings | indent 4 }}
    {{- end }}
{{ end }}
{{- end }}
