{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and (not .Values.pachd.enterpriseSecretSecretName) (include "pachyderm.enterpriseLicenseKeySecretName" . ) }} 
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-enterprise
  namespace: {{ .Release.Namespace }}
stringData:
  enterprise-secret: {{ default (randAlphaNum 32) .Values.pachd.enterpriseSecret }}
{{- end }}
