{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pachyderm-identity-config
  namespace: {{ .Release.Namespace }}
data:
  identity-config: |  
    issuer: {{ include "pachyderm.issuerURI" . }}
    id_token_expiry: {{ .Values.oidc.IDTokenExpiry }}
    rotation_token_expiry: {{ .Values.oidc.RotationTokenExpiry }}
  oidc-clients: |
    - id: {{ .Values.pachd.oauthClientID }}
      name: {{ .Values.pachd.oauthClientID }}
      redirect_uris:
      - {{ include "pachyderm.pachdRedirectURI" . }}
      trusted_peers:
      {{- if .Values.console.enabled}}
      - {{ .Values.console.config.oauthClientID | quote }}
      {{- end }}
      {{- if .Values.determined.enabled}}
      - {{ default "determined" .Values.determined.oidc.clientId }}
      {{- end }}
    {{- if .Values.console.enabled }}
    - id: {{ .Values.console.config.oauthClientID }}
      name: {{ .Values.console.config.oauthClientID  }}
      redirect_uris:
      - {{ include "pachyderm.consoleRedirectURI" . | quote }}
    {{- end }}
    {{- if .Values.determined.enabled }}
    - id: {{ default "determined" .Values.determined.oidc.clientId }}
      name: {{ default "determined" .Values.determined.oidc.clientId }}
      redirect_uris:
      - {{ required "A valid recipient url is required!" (printf "%s/oidc/callback" .Values.determined.oidc.idpRecipientUrl) }}
    {{- end }}
  trusted-peers: |
{{ toYaml .Values.pachd.additionalTrustedPeers | indent 4 }}
