apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
  name: modeldb-backend-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: modeldb
    tier: backend-proxy
  type: LoadBalancer
