apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: seldon-core-operator  
  app.kubernetes.io/instance: seldon-core-operator
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: seldon
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
