{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.cloudsqlAuthProxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudsql-auth-proxy
    suite: pachyderm
  name: cloudsql-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: cloudsql-auth-proxy
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      labels:
        app: cloudsql-auth-proxy
        suite: pachyderm
        {{- if .Values.cloudsqlAuthProxy.podLabels }}
        {{- toYaml .Values.cloudsqlAuthProxy.podLabels | nindent 8 }}
        {{- end }}
      name: cloudsql-auth-proxy
      namespace: {{ .Release.Namespace }}
    spec:
      {{- if .Values.cloudsqlAuthProxy.priorityClassName }}
      priorityClassName: {{ .Values.cloudsqlAuthProxy.priorityClassName }}
      {{- end }}
      serviceAccountName: k8s-cloudsql-auth-proxy
{{- include "pachyderm.imagePullSecrets" . | indent 6 }}
      containers:
      - name: cloud-sql-proxy
        image: {{ .Values.cloudsqlAuthProxy.image.repository }}:{{ .Values.cloudsqlAuthProxy.image.tag }}
        ports:
        - containerPort: {{ .Values.cloudsqlAuthProxy.port }}
        env:
        - name: CSQL_PROXY_INSTANCE_CONNECTION_NAME
          value: "{{ .Values.cloudsqlAuthProxy.connectionName }}"
        - name: CSQL_PROXY_PORT
          value: "{{ .Values.cloudsqlAuthProxy.port }}"
        - name: CSQL_PROXY_ADDRESS
          value: "0.0.0.0"
          {{- if .Values.cloudsqlAuthProxy.iamLogin }}
        - name: CSQL_PROXY_AUTO_IAM_AUTHN
          value: "true"
          {{- end }}
        resources: {{ toYaml .Values.cloudsqlAuthProxy.resources | nindent 10 }}
      {{- if .Values.global.securityContexts.enabled }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
              drop:
              - all
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      {{- if .Values.cloudsqlAuthProxy.nodeSelector }}
      nodeSelector: {{ toYaml .Values.cloudsqlAuthProxy.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.cloudsqlAuthProxy.tolerations }}
      tolerations: {{ toYaml .Values.cloudsqlAuthProxy.tolerations | nindent 8 }}
      {{- end }}
{{ end -}}
