apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: oidc-authservice
  app.kubernetes.io/instance: oidc-authservice-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: oidc-authservice
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
kind: Kustomization
namespace: istio-system
resources:
- overlays/application/application.yaml
