apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: api-service
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ''
    keywords:
    - api-service
    - kubeflow
    links:
    - description: About
      url: ''
    maintainers: []
    owners: []
    type: api-service
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: api-service
      app.kubernetes.io/instance: api-service-0.2.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: api-service
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.2.0
